### ISSUE TITLE
How to refresh

### ISSUE THREAD

**Issue by coreyperkins** [alwinn1977/react-simple-jstree#3]
In my render() upon a state change I return 

`<TreeView treeData={data} />`

However, the jstree does not appear to refresh. I've tried using jstree's functions destroy and refresh without any luck.

Are there any examples that do this?

Thanks!

**Comment by PGDJ** [comment]
It doesn't support that, if you would like to you will have to make changes to the jstree in the src $('#data').jstree(true).refresh();

edit I'm seeing you used refresh. Could you clarify what code you are exactly running?

**Comment by coreyperkins** [comment]
v0.0.3

Here's the code in my render(). 

```
    var data =  'core' : {
        'check_callback' : true,
        'data' : treeData
      },
      'plugins': ['types']
    };
    
    return (
      <TreeView treeData={data} />
    );
```

treeData is just an array of jstree nodes.

edit: I did the refresh inside the componentDidUpdate ->  componentDidUpdate() { $('#data').jstree(true).refresh(); }

**Comment by alwinn1977** [comment]
Refresh feature was added in 0.1.0. See demo app in demo folder.

**Comment by coreyperkins** [comment]
Great work! This works perfectly.
