### ISSUE TITLE
Recommended way to handle select_node.jstree event

### ISSUE THREAD

**Issue by coreyperkins** [alwinn1977/react-simple-jstree#4]
Currently I am wiring up the 'select_node.jstree' event in the componentDidUpdate of the react component that wraps the TreeView like so:

`componentDidUpdate() {
    console.log('componentDidUpdate on TreeView container');
    
    var $this = this;

    $('#data').on("select_node.jstree", function (event, data) {
      var id = data.node.id === 'root' ? '00000000-0000-0000-0000-000000000000' : data.node.id;

      $this.props.updateSelectedTreeNode(id, data.node.original.type);
    });
  }`

This has the adverse effect of being hooked up multiple times if you click repeatedly through the tree. I also tried componentDidMount(), but I believe that to be too early in the lifecycle to actually be hooked up, as I saw no evidence the handler was properly attached.

Any recommendations? 

Thanks!

**Comment by alwinn1977** [comment]
Hello, upgrade component to 0.2.0 and use onChange prop. See example in demo folder for details.

**Comment by coreyperkins** [comment]
This does work, but I wanted to provide some feedback. This feels like it is by design.

I noticed that the handler is hit three times with the following actions (in order): select_node, deselect_all, and select_node. My assumption is that this comes from jstree and it's a built in series of actions to first clear any previously selected nodes, however, I do wonder why it fires select_node twice and why it is first in the sequence. I would expect it to be deselect_all then select-node.

Anyway, this works great and it is much cleaner code than what I was using. Thanks a ton!
